spring:
   profiles:
     active: -defult
   datasource:
     url: jdbc:mysql://localhost:3306/hse_eqzj?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=GMT%2B8
     driver-class-name: com.mysql.jdbc.Driver
     data-password: root
     name: root





---
spring:
   profiles:
         active: -dev
   datasource:
         jdbc-url: jdbc:mysql://localhost:3306/hse_eqzj?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=GMT%2B8
         username: root
         password: root
         driver-class-name: com.mysql.cj.jdbc.Driver


